name: Monitor Openprovider nameservers

on:
  schedule:
  - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Monitor
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: .github/scripts/monitor-nameservers.sh
